#!/bin/bash
#
# Copyright (c) 2022 YoyoOS packaging team
#
# This file is part of yoyo-packaging-bot
#
# This script is free software; you can redistribute it and/or
# modify it under the terms of the  GNU AFFERO GENERAL PUBLIC LICENSE Version 3
# as published by the Free Software Foundation and appearing in the file LICENSE
# included in the packaging of this file.
#

set -e

. ${SCRIPT_DIR}/functions/logging

# get new request
mirror_new_request() {

}


# get new package
# parameter: auth_token 
mirror_new_pacakge() {
	bot_log d "new_package" "get new package"
}

