#!/bin/bash
#
# Copyright (c) 2022 YoyoOS packaging team
#
# This file is part of yoyo-packaging-bot
#
# This script is free software; you can redistribute it and/or
# modify it under the terms of the  GNU AFFERO GENERAL PUBLIC LICENSE Version 3
# as published by the Free Software Foundation and appearing in the file LICENSE
# included in the packaging of this file.
#

set +e

SCRIPT_DIR=$(dirname $(cd $(dirname $0); pwd))

. ${SCRIPT_DIR}/config/mirror_config
[ -f ${SCRIPT_DIR}/config/mirror_config_usr ] && . ${SCRIPT_DIR}/config/mirror_config_usr

[ -z "${MIRROR_TOKEN}" ] && echo No MIRROR_TOKEN && exit 1

# end http request
# parameter: code msg
end_request() {
	# make remote closed
	echo "HTTP/1.1 ${1} ${2}"
	echo 'Content-Type: text/plain'
	echo 'Content-Length: 0'
	echo
}

read line
[ "${line}" != "GET / HTTP/1.1" ] && exit 0
# read headers
while read line; do
	# headers end
	if [ "${line}" == "" ]; then break; fi
	key=$(echo ${line} | sed 's/^\(.*\): \(.*\)$/\1/')
	value=$(echo ${line} | sed 's/^\(.*\): \(.*\)$/\2/')
	if [ "${key}" == "Content-Length" ] && [ "${value}" != "0" ]; then
		end_request 400 "Bad Request"
		exit 0
	elif [ "${key}" == "X-YOYO-MIRROR-BOT-TOKEN" ]; then
		REQUEST_TOKEN=${value}
		if [ "${REQUEST_TOKEN}" != "${MIRROR_TOKEN}" ]; then
			end_request 403 "Forbidden"
			exit 0
		fi
	fi
done
unset key value

if [ -z "${REQUEST_TOKEN}" ]; then
	end_request 403 "Forbidden"
	exit 0
fi

# ignore rest
end_request 200 OK

# redirect file discriptor
exec >&2

set -e

. ${SCRIPT_DIR}/functions/mirror

mirror_new_request

