#!/bin/bash
#
# Copyright (c) 2022 YoyoOS packaging team
#
# This file is part of yoyo-packaging-bot
#
# This script is free software; you can redistribute it and/or
# modify it under the terms of the  GNU AFFERO GENERAL PUBLIC LICENSE Version 3
# as published by the Free Software Foundation and appearing in the file LICENSE
# included in the packaging of this file.
#

set -e

SCRIPT_DIR=$(cd $(dirname $0); pwd)

. ${SCRIPT_DIR}/config/mirror_config
[ -f ${SCRIPT_DIR}/config/mirror_config_usr ] && . ${SCRIPT_DIR}/config/mirror_config_usr

[ -z "${SERVER_PORT}" ] && echo No server port set && ecit 1
[ -z "${SERVER_RANGE}" ] && echo No server ip range set && exit
[ -z "${MIRROR_TOKEN}" ] && echo No MIRROR_TOKEN && exit 1

socat -v -d -d TCP-LISTEN:${SERVER_PORT},crlf,reuseaddr,fork,range=${SERVER_RANGE} \
		SYSTEM:"bash ${SCRIPT_DIR}/functions/request_handler"

